version: '2'
services:
  node01:
    image: percona/percona-xtradb-cluster
    container_name: pxc_node01
    networks:
      pxc_network:
        ipv4_address: 172.24.0.2
    environment:
            CLUSTER_NAME: test_cluster
            MYSQL_ROOT_PASSWORD: root
            XTRABACKUP_PASSWORD: sst_pass
            CLUSTER_JOIN:
  node02:
    image: percona/percona-xtradb-cluster
    container_name: pxc_node02
    networks:
      pxc_network:
        ipv4_address: 172.24.0.3
    environment:
            CLUSTER_NAME: test_cluster
            MYSQL_ROOT_PASSWORD: root
            XTRABACKUP_PASSWORD: sst_pass
            CLUSTER_JOIN: '172.24.0.2'
    depends_on:
      - node01
  node03:
    image: percona/percona-xtradb-cluster
    container_name: pxc_node03
    networks:
      pxc_network:
        ipv4_address: 172.24.0.4
    environment:
            CLUSTER_NAME: test_cluster
            MYSQL_ROOT_PASSWORD: root
            XTRABACKUP_PASSWORD: sst_pass
            CLUSTER_JOIN: '172.24.0.3'
    depends_on:
      - node02

networks:
  pxc_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
          gateway: 172.24.0.1

