    version: '2'
    services:
      node01:
        image: percona/percona-xtradb-cluster
        environment:
                CLUSTER_NAME: test_cluster
                MYSQL_ROOT_PASSWORD: mysql_pass
                XTRABACKUP_PASSWORD: sst_pass
                CLUSTER_JOIN:
      node02:
        image: percona/percona-xtradb-cluster
        environment:
                CLUSTER_NAME: test_cluster
                MYSQL_ROOT_PASSWORD: mysql_pass
                XTRABACKUP_PASSWORD: sst_pass
                CLUSTER_JOIN: '172.18.0.2'
        depends_on:
          - node01
      node03:
        image: percona/percona-xtradb-cluster
        environment:
                CLUSTER_NAME: test_cluster
                MYSQL_ROOT_PASSWORD: mysql_pass
                XTRABACKUP_PASSWORD: sst_pass
                CLUSTER_JOIN: '172.18.0.3'
        depends_on:
          - node02

